apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: prometheus-custom-metrics-example
  name: prometheus-custom-metrics-example
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: prometheus-custom-metrics-example
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "5000"
        prometheus.io/scrape: "true"
      labels:
        k8s-app: prometheus-custom-metrics-example
    spec:
      containers:
        - name: test
          image: wooos/prometheus-custom-metrics-example:1.0.0